- name: Installing Maven
  ansible.builtin.yum:
    name: maven
    state: latest

- name: Import app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Installing Maven Dependencies
  ansible.builtin.shell: mvn clean package ;mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app


- name: Load Mysql Schema
  ansible.builtin.import_tasks:
    file: mysql_schema_setup.yml

- name: Copying Service File
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Service restarting and enabling
  ansible.builtin.include_tasks:
    file: app_start.yml