- name: Installing python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: latest

- name: Import app_presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Installing python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: app_start.yml

